### ISSUE TITLE
Undesirable addition space

### ISSUE THREAD

**Issue by dymn** [xkbmon/xkbmon#2]
Sometimes, the pattern has not been revealed, the output is supplemented to the right of the language sign with spaces (tabs?) for 3-4 characters of empty space.

Maybe, but I'm not sure, this happens after wake up from sleep mode or killing and re-run compton (for gaming).

Gentoo x64, tint2-17.0.2, openbox.

**Comment by noscript** [comment]
Can you reproduce this while running xkbmon in terminal?

**Comment by dymn** [comment]
Сергей, запустил я xkbmon  в терминале, но проблемный выхлоп не виден или эти пробелы (или что там) сливаются с фоном. Ошибок никаких нет.
Заметил, что проблема появляется в tint2 после включения хранителя экрана (xfce4-screensaver), а затем выключения монитора. Возможно, проблема не в xkbmon, а в tint2, но он заморожен. Может это сам tint2 добавляет после символов раскладки пустое расстояние? Но, с другой стороны, это только с xkbmon (но и повреждается иконка corectrl, лечится только перезапуском tint2).

![2023-04-12_11-51](https://user-images.githubusercontent.com/20149245/231405799-0394d030-4b57-4f0f-bd8e-ec39d5bd2676.png)

**Comment by noscript** [comment]
Привет! Попробуйте заключить вывод в кавычки и попереключать раскладку:
```
$ xkbmon | awk '{print "\x27" $1 "\x27" }'
'us'
'ru'
'us'
'ru'
'us'
```

**Comment by dymn** [comment]
Добрый день!
Все норм на выхлопе xkbmon. Закралось подозрение, что все портит xxkb, хотя и настроен он на работу без иконки в трее, но видно каким-то образом всплывает в трей. Буду конфигурировать заново. 

kbdd  - глючный, забывает раскладки, заброшен.
xxkb - заброшен еще раньше, если он в трее, то при смене разрешения иконка пропадает, хотя сам в памяти и работает. Зато позволяет задать определенную раскладку приложениям.
gxkb - ушел в политоту, удалил поддержку русского и белорусского языков, да и мало ли что там еще начудил.

Потому и xkbmon, но нужно что-то, что помнит раскладки пооконно.

**Comment by noscript** [comment]
>но нужно что-то, что помнит раскладки пооконно

В принципе, можно написать маленький демон, который бы мониторил смену фокуса и запоминал/восстанавливал раскладку.

**Comment by dymn** [comment]
Сейчас получается, что вообще нет корректно работающих программ про это. Все заброшено и жутко старое.
